### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by ignatenkobrain** [hannobraun/inotify-sys#12]
It is requirement when packaging for various Linux distributions.

**Comment by hannobraun** [comment]
Hey, sorry for the late reply.

Thank you for bringing this to my attention. This project is licensed under the ISC license, which is included in the README. But of course it would be better to add it in a dedicated LICENSE file.

I'll do it next time I work on inotify-rs (which might be a while). In the meantime, I'm happy to accept a pull request that adds a LICENSE.
